nvidia-detect/README
nvidia-detect/nvidia-detect.c

This should help with some of the redirection and error issues.

Warnings and errors to STDERR

---

nvidia-detect/nvidia-detect.c

This extra output data for -l may come in handy for some users.

make -l also provide the name of the kmod

---

bbswitch/el7/bbswitch.spec
bbswitch/el7/kmodtool-bbswitch-el7.sh
netatop-utils/el7/netatop.modules

Fixed bbswitch, requires was wrong, this is now /usr/sbin/depmod

fixed bbswitch

---

bbswitch/el7/bbswitch.conf
bbswitch/el7/bbswitch.spec
bumblebee/el7/bumblebee.conf
bumblebee/el7/bumblebeed.service

Selinux policy is coming soon, will be a new package, needs more testing.

fixed bbswitch and bumblebee

---

bumblebee/el7/bumblebee.spec
selinux-bumblebee/el7/bumblebee-bbswitch.if
selinux-bumblebee/el7/bumblebee-bbswitch.te
selinux-bumblebee/el7/selinux-bumblebee.spec

Created a custom selinux policy for bumblebee, so it can interact with bbswitch.
It's a seperate package, so easier to maintain.

Create new package with custom selinux policy for bumblebee

---

kmod-pf_ring/SOURCES/kmodtool-pf_ring-el6.sh
kmod-pf_ring/pf_ring-kmod.spec

added pf_ring module initial packaging

---

bumblebee/el7/bumblebee.spec

bumblebee spec file: minor correction on a date line in changelog

minor correction on a date in changelog

---

fglrx-kmod/el6/fglrx-kmod.spec

Nothing fancy, just the new upstream version released 2 weeks ago

update to 15.5

---

fglrx-x11-drv/el6/fglrx-x11-drv.spec

Signed-off-by: Manuel Wolfshant <wolfy@fedoraproject.org>

update Catalyst drivers to Omega 15.5

---

drbd84-utils/el7/drbd.ocf.patch
drbd84-utils/el7/drbd84-utils.spec

Update drbd.ocf to the one from 8.9.3-2.

Patching drbd84-utils.

---

bbswitch/el7/bbswitch.spec
bbswitch/el7/kmodtool-bbswitch-el7.sh

Signed-off-by: Akemi Yagi <akemi@toracat.org>

rebuild bbswitch against el7.2 kernel

---

i2c-i801-kmod/el7/kmodtool-i2c-i801-el7.sh

I installed the related source RPM, and this shell script is part of it. So maybe it could be added to the github sources also. I didn't change the sh content, it's just the same which is part of the source RPM.

added required shell script

---

drbd84-kmod/el7/drbd84-kmod.spec
drbd84-utils/el7/drbd84-utils.spec

update to drbd-8.4.8 & drbd-utils-8.9.8

drbd-8.4.8 & drbd-utils-8.9.8

---

drbd90-utils/el7/elrepo-selinux-bug695.patch

drbd90-utils : adding elrepo-selinux-bug695.patch

---

drbd84-utils/el7/elrepo-selinux-bug695.patch

drbd84-utils: adding elrepo-selinux-bug695.patch

---

ixgbevf/el6/GPL-v2.0.txt
ixgbevf/el6/ixgbevf-kmod.spec
ixgbevf/el6/kmodtool-ixgbevf-el6.sh

Signed-off-by: Akemi Yagi <toracat@elrepo.org>

ixgbevf-kmod added

---

rtl818x_pci/el7/GPL-v2.0.txt
rtl818x_pci/el7/kmodtool-rtl818x_pci-el7.sh
rtl818x_pci/el7/rtl8180-kmod.spec

Signed-off-by: Akemi Yagi <toracat@elrepo.org>

rtl8180-kmod added

---

ixgbevf/el7/GPL-v2.0.txt
ixgbevf/el7/ixgbevf-kmod.spec
ixgbevf/el7/kmodtool-ixgbevf-el7.sh

Signed-off-by: Akemi Yagi <toracat@elrepo.org>

ixgbevf-kmod el7 added

---

drbd90-kmod/el7/drbd90-kmod.spec
drbd90-kmod/el7/kmodtool-drbd90-el7.sh
drbd90-utils/el7/drbd90-utils.spec

Signed-off-by: Akemi Yagi <toracat@elrepo.org>

drbd90 kmod utils update

---

drbd90-kmod/el7/drbd90-kmod.spec
drbd90-kmod/el7/kmodtool-drbd90-el7.sh
drbd90-utils/el7/drbd90-utils.spec

drbd90 for el7

---

drbd84-utils/el7/drbd84-utils.spec

drbd84-utils for el7

---

drbd84-kmod/el7/drbd84-kmod.spec
drbd84-kmod/el7/kmodtool-drbd84-el7.sh
drbd84-utils/el7/drbd84-utils.spec
drbd90-kmod/el7/drbd90-kmod.spec
drbd90-kmod/el7/kmodtool-drbd90-el7.sh
drbd90-utils/el7/drbd90-utils.spec

Updating drbd84 and drbd80 for el7

Updating drbd84 and drbd80 for el7

---

xpad-kmod/el7/kmodtool-xpad-el7.sh
xpad-kmod/el7/xpad-kmod.spec

update xpad to el7_6

---

usbip-kmod/el7/ELRepo-usbip-1.0.1-Makefile.patch
usbip-kmod/el7/GPL-v2.0.txt
usbip-kmod/el7/kmodtool-usbip-el7.sh
usbip-kmod/el7/usbip-kmod.spec
usbip-kmod/el7/usbip_common_h_7_6.patch

usbip-kmod added

---

i2c-i801-kmod/el7/i2c-i801-kmod.spec
i2c-i801-kmod/el7/kmodtool-i2c-i801-el7.sh

i2c-i801 updated to 7_6

---

e1000e-kmod/el8/e1000e-kmod.spec

e1000e el8 initial build

---

reiserfs-kmod/el7/elrepo-reiserfs-fix-redefine-error.patch
reiserfs-kmod/el7/elrepo-reiserfs-random.patch
reiserfs-kmod/el7/kmodtool-reiserfs-el7.sh
reiserfs-kmod/el7/reiserfs-kmod.spec

reiserfs (new in git) and 8188eu update.

reiserfs and 8188eu

---

e1000e-kmod/el8/e1000e-kmod.spec

e1000e(el8) adjusted for EL8.0 GA

e1000e(el8) adjusted for EL8.0 GA

---

forcedeth-kmod/el8/forcedeth-kmod.spec

forcedeth(el8) adjusted for EL8.0 GA

forcedeth(el8) adjusted for EL8.0 GA

---

r8822be-kmod/el8/r8822be-kmod.spec

r8822be-kmod el8 initial build

r8822be-kmod el8 initial build

---

ixgbe-kmod/el7/ixgbe-kmod.spec
ixgbe-kmod/el7/kmodtool-ixgbe-el7.sh

ixgbe-kmod el7

---

xpad-kmod/el7/kmodtool-xpad-el7.sh
xpad-kmod/el7/xpad-kmod.spec

xpad-kmod: update to 7.7

---

usbip-kmod/el7/kmodtool-usbip-el7.sh
usbip-kmod/el7/usbip-kmod.spec

usbip-kmod: update to 7.7

---

sata_sil/el8/GPL-v2.0.txt
sata_sil/el8/elrepo-libata-eh.patch
sata_sil/el8/sata_sil-kmod.spec
sata_sil/el8/scsi_transport_api.h

sata_sil: el8 initial build

---

zd1211rw-kmod/el7/kmodtool-zd1211rw-el7.sh
zd1211rw-kmod/el7/zd1211rw-kmod.spec

zd1211rw-kmod: rebuilt against RHEL 7.7 kernel

---

ixgbe-kmod/el7/elrepo-bug938.patch
ixgbe-kmod/el7/ixgbe-kmod.spec

Applied patch from kernel.org commit 377228accbbb8b9738f615d791aa803f41c067e0
(https://elrepo.org/bugs/view.php?id=938)

ixgbe-kmod: update to 5.6.3-2

---

cciss-kmod/el7/Documentation/ABI/testing/sysfs-bus-pci-devices-cciss
cciss-kmod/el7/Documentation/blockdev/cciss.txt
cciss-kmod/el7/GPL-v2.0.txt
cciss-kmod/el7/cciss-kmod.spec
cciss-kmod/el7/drivers/block/Kconfig
cciss-kmod/el7/drivers/block/Makefile
cciss-kmod/el7/drivers/block/cciss.c
cciss-kmod/el7/drivers/block/cciss.h
cciss-kmod/el7/drivers/block/cciss_cmd.h
cciss-kmod/el7/drivers/block/cciss_scsi.c
cciss-kmod/el7/drivers/block/cciss_scsi.h
cciss-kmod/el7/include/linux/cciss_ioctl.h
cciss-kmod/el7/include/uapi/linux/cciss_defs.h
cciss-kmod/el7/include/uapi/linux/cciss_ioctl.h
cciss-kmod/el7/kmodtool-cciss-el7.sh

cciss-kmod: el7 added, cciss-kmod-3.6.26-7.el7_7

---

mptfc-kmod/el8/Kconfig
mptfc-kmod/el8/Makefile
mptfc-kmod/el8/lsi/mpi.h
mptfc-kmod/el8/lsi/mpi_cnfg.h
mptfc-kmod/el8/lsi/mpi_fc.h
mptfc-kmod/el8/lsi/mpi_history.txt
mptfc-kmod/el8/lsi/mpi_init.h
mptfc-kmod/el8/lsi/mpi_ioc.h
mptfc-kmod/el8/lsi/mpi_lan.h
mptfc-kmod/el8/lsi/mpi_log_fc.h
mptfc-kmod/el8/lsi/mpi_log_sas.h
mptfc-kmod/el8/lsi/mpi_raid.h
mptfc-kmod/el8/lsi/mpi_sas.h
mptfc-kmod/el8/lsi/mpi_targ.h
mptfc-kmod/el8/lsi/mpi_tool.h
mptfc-kmod/el8/lsi/mpi_type.h
mptfc-kmod/el8/mptbase.c
mptfc-kmod/el8/mptbase.h
mptfc-kmod/el8/mptctl.c
mptfc-kmod/el8/mptctl.h
mptfc-kmod/el8/mptdebug.h
mptfc-kmod/el8/mptfc-kmod.spec
mptfc-kmod/el8/mptfc.c
mptfc-kmod/el8/mptlan.c
mptfc-kmod/el8/mptlan.h
mptfc-kmod/el8/mptsas.c
mptfc-kmod/el8/mptsas.h
mptfc-kmod/el8/mptscsih.c
mptfc-kmod/el8/mptscsih.h
mptfc-kmod/el8/mptspi.c

mptfc-kmod el8, new package

---

sata_sis-kmod/el8/GPL-v2.0.txt
sata_sis-kmod/el8/elrepo-libata-eh.patch
sata_sis-kmod/el8/sata_sis-kmod.spec
sata_sis-kmod/el8/scsi_transport_api.h

sata_sis-kmod el8: new package

---

pata_sis-kmod/el8/GPL-v2.0.txt
pata_sis-kmod/el8/elrepo-libata-eh.patch
pata_sis-kmod/el8/pata_sis-kmod.spec
pata_sis-kmod/el8/scsi_transport_api.h

pata_sis-kmod el8: new package

---

3w-9xxx-kmod/el8/3w-9xxx-kmod.spec
3w-9xxx-kmod/el8/3w-9xxx.c
3w-9xxx-kmod/el8/3w-9xxx.h
3w-9xxx-kmod/el8/Makefile

3w-9xxx-kmod el8: new package

---

3w-sas-kmod/el8/3w-sas-kmod.spec
3w-sas-kmod/el8/3w-sas.c
3w-sas-kmod/el8/3w-sas.h
3w-sas-kmod/el8/Makefile

3w-sas-kmod el8: new package

---

be2net-kmod/el8/GPL-v2.0.txt
be2net-kmod/el8/Kconfig
be2net-kmod/el8/Makefile
be2net-kmod/el8/be.h
be2net-kmod/el8/be2net-kmod.spec
be2net-kmod/el8/be_cmds.c
be2net-kmod/el8/be_cmds.h
be2net-kmod/el8/be_ethtool.c
be2net-kmod/el8/be_hw.h
be2net-kmod/el8/be_main.c
be2net-kmod/el8/be_roce.c
be2net-kmod/el8/be_roce.h

be2net-kmod el8: new package

---

drbd90-kmod/el8/drbd90-kmod.spec
drbd90-utils/el8/drbd90-utils.spec
drbd90-utils/el8/elrepo-selinux-bug695.patch

drbd90-kmod, drbd90-utils for el8.1

---

3w-9xxx-kmod/el8/3w-9xxx-kmod.spec

kmod-3w-9xxx: rebuilt for RHEL 8.1

---

be2net-kmod/el8/be2net-kmod.spec
be2net-kmod/el8/be_main.c

kmod-be2net: rebuilt for RHEL 8.1

---

isci-kmod/el8/isci-kmod.spec

kmod-isci: rebuilt against RHEL 8.1

---

mptfc-kmod/el8/mptfc-kmod.spec
mptfc-kmod/el8/mptsas.c
mptfc-kmod/el8/mptspi.c

kmod-mptfc: updated to RHEL 8.1

---

sata_sil-kmod/el8/sata_sil-kmod.spec

kmod-sata_sil: update to RHEL 8.1

---

sata_sis-kmod/el8/sata_sis-kmod.spec

kmod-sata_sis: rebuilt against RHEL 8.1

---

pata_sis-kmod/el8/pata_sis-kmod.spec

kmod-pata_sis: updated to RHEL 8.1

---

pata_amd-kmod/el8/elrepo-libata-eh.patch
pata_amd-kmod/el8/pata_amd-kmod.spec
pata_amd-kmod/el8/scsi_transport_api.h

Initial build for EL 8.0.
https://elrepo.org/bugs/view.php?id=973

kmod-pata_sis: new for el8.0

---

reiserfs-kmod/el8/reiserfs-kmod.spec

Source code from RHEL 8.0 kernel.

kmod-reiserfs: initial build for el8

---

pata_amd-kmod/el8/elrepo-libata.patch
pata_amd-kmod/el8/pata_amd-kmod.spec

kmod-pata: update to 8.1

---

reiserfs-utils/el8/reiserfs-utils.spec

reiserfs-utils: initial build for EL8

---

wireguard-kmod/el7/GPL-v2.0.txt
wireguard-kmod/el7/kmodtool-wireguard-el7.sh
wireguard-kmod/el7/wireguard-kmod.spec

wireguard-kmod el7: initial release

---

wireguard-kmod/el8/GPL-v2.0.txt
wireguard-kmod/el8/wireguard-kmod.spec

wireguard-kmod el8: initial release

---

mt7601u-kmod/el7/GPL-v2.0.txt
mt7601u-kmod/el7/kmodtool-mt7601u-el7.sh
mt7601u-kmod/el7/mt7601u-kmod.spec

Built against RHEL 7.7 kernel.

mt7601u-kmod: el7 initial release

---

drbd90-kmod/el7/drbd90-kmod.spec
drbd90-kmod/el7/kmodtool-drbd90-el7.sh

- Updated to 9.0.20
- Rebuild against RHEL 7.7 kernel

kmod-drbd90: el7 update

---

drbd90-utils/el7/drbd90-utils.spec

drbd90-utils: el7 update to 9.10.0

---

drbd84-kmod/el7/drbd84-kmod.spec
drbd84-kmod/el7/kmodtool-drbd84-el7.sh
drbd84-utils/el7/drbd84-utils.spec
drbd90-kmod/el7/drbd90-kmod.spec
drbd90-kmod/el7/kmodtool-drbd90-el7.sh
drbd90-utils/el7/drbd90-utils.spec

drbd84 and drbd90 and respective -utils packages updated for EL 7.8.

drbd84 and drbd90: updated for EL7.8

---

mt7601u-kmod/el7/kmodtool-mt7601u-el7.sh
mt7601u-kmod/el7/mt7601u-kmod.spec

kmod-mt7601u: rebuilt for el7.8

---

wireguard-kmod/el7/kmodtool-wireguard-el7.sh
wireguard-kmod/el7/wireguard-kmod.spec
wireguard-kmod/el8/wireguard-kmod.spec

Update wireguard kmod to 1.0.20200413
